### ISSUE TITLE
Hard line breaks within paragraphs

### ISSUE THREAD

**Issue by jvirtanen** [ianks/octodown#103]
With Octodown 1.8.5, there is a difference in how Octodown and GitHub treat hard line breaks within paragraphs. An example Markdown document:
```markdown
This should render as
one line.
```
On GitHub that renders as follows:

> This should render as one line.

However, with Octodown 1.8.5 that renders as follows:

> This should render as\
one line.

The GitHub interpretation appears to be in line with the original [Markdown syntax documentation](https://daringfireball.net/projects/markdown/syntax#p).

**Comment by ianks** [comment]
Thanks for the report! I believe this would be same as the `:NOBREAKS` option from https://github.com/gjtorikian/commonmarker#render-options. I'm really busy for the next couple of weeks, could you try to add that option and see if it emits the expected markdown?

**Comment by jvirtanen** [comment]
@ianks Thanks for the quick response! I'll give it a try. 👍
