### ISSUE TITLE
bitbucket support

### ISSUE THREAD

**Issue by kpurdon** [ianks/octodown#22]
Add support for bitbucket markdown preview.

**Comment by mlr** [comment]
👎

Defeats the purpose and name of this project. Especially since you can pipe like a standard Unix command. I'd rather have it do one thing really well. Namely create github markdown previews only.

**Comment by kpurdon** [comment]
@mlr  I'm not sure I agree. 

The name: What does "octodown" have do with with github markdown specifically?
The purpose: A command-line markdown rendering tool. 

It already supports multiple types (github, atom) why not another VERY popular one?

While I do agree with the unix philosophy "do one thing well" I think that one thing is "render markdown previews from the command line".
