### ISSUE TITLE
Package with Traveling Ruby

### ISSUE THREAD

**Issue by FooBarWidget** [ianks/octodown#29]
Not all of your users are Ruby programmers, and those who are not Ruby programmers may have trouble installing Octodown. Maybe you can package Octodown with [Traveling Ruby](http://phusion.github.io/traveling-ruby/) to solve this problem.

**Comment by ianks** [comment]
Wow this looks very promising. I was actually researching ways to do this and could not come up with a solution I liked. Glad you brought this to my attention.

My main goal is releasing on Homebrew and other package managers. Have you had success doing that before with Traveling Ruby?

**Comment by FooBarWidget** [comment]
It shouldn't be hard. With Traveling Ruby, your baseline would be to create binary tarballs for Linux and OS X. Once you have these, you can:

 1. Write a Homebrew recipe that simply downloads & extracts the OS X Octodown binary tarball and creates bin wrapper scripts.
 2. Create RPMs and DEBs that contain the contents of the Linux binary tarball (maybe in /opt/octodown), plus some wrapper scripts in /usr/bin. This approach would not comply to the Linux distributions' packaging guidelines at all, so you wouldn't be able to get them included into Debian/Ubuntu/Fedora/RHEL, but it would make your RPM/DEB packaging efforts literally 10 times easier. You no longer have to create different RPMs/DEBs for each distro: you just create a generic RPM/DEB that works on all Red Hat-based distros and all Debian-based distros.

**Comment by andrewhavens** [comment]
:+1: I like this idea!

**Comment by ianks** [comment]
Should have this PR within the next day or two. Then it is onto the Homebrew package, which I hope they approve of.

**Comment by ianks** [comment]
PR is here: https://github.com/ianks/octodown/pull/38

**Comment by ches** [comment]
I think this could be closed since #38 is merged? :grin:

**Comment by ianks** [comment]
Yes @ches you are right. Thanks for the heads up.
