### ISSUE TITLE
Can't open temp file on OS X

### ISSUE THREAD

**Issue by jlecour** [ianks/octodown#34]
Hi,

On Yosemite (10.10.1), the temp file looks like `octodown20150115-80952-1ab8xc5` without any extension.

The `open` command opens the file in the browser, but it renders a white page and opens a Finder window for the base directory of the temp file.

If an extension is set (`.html` for example) the browser (Safari for instance) opens the file just fine.

**Comment by tony-f** [comment]
I am experiencing the same thing as @jlecour including adding .html to the temp file and being able to view it fine in Safari.

**Comment by ianks** [comment]
This should be fixed in `v1.0.4` by https://github.com/ianks/octodown/pull/35

Thanks for the help!
