### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by BrendanThompson** [ianks/octodown#39]
It would be awesome if you could export the result to PDF. I find my self wishing that I was able to use GitHub formatted MD for documents, but nothing does it justice except for Octodown!

**Comment by ianks** [comment]
Hmm that could be interesting. I'll have a look at HTML to PDF converters soon.

**Comment by americodls** [comment]
:+1:

**Comment by FooBarWidget** [comment]
I recommend [wkhtmltopdf](http://wkhtmltopdf.org/). The [prawn](http://prawnpdf.org/api-docs/1.3/) gem is a Ruby wrapper around it.

**Comment by americodls** [comment]
Hi guys.

I used to use this command for generates pdf from octodown:
```shell
octodown --raw README.md | wkhtmltopdf - README.pdf
```
So I decided to try to make things easier and made my proposal here: #66 .

What do you think ?
