### ISSUE TITLE
Traveling Ruby package contains unsupported native extensions

### ISSUE THREAD

**Issue by FooBarWidget** [ianks/octodown#46]
In your Traveling Ruby package you're using quite a few unsupported native extensions (extensions for which Traveling Ruby provides no binaries). Thus, your package may not work everywhere.

 * [x] rugged
 * [x] posix-spawn
 * [x] nokogumbo
 * [x] github-markdown
 * [x] escape_utils
 * [x] charlock_holmes

I found out by scanning for '*.bundle' files inside lib/app/vendor/ruby/2.1.0/gems.

**Comment by FooBarWidget** [comment]
Indeed, your OS X package doesn't work for me because some of the native extensions are not compiled to be portable.

```
$ octodown-1.0.4-osx/octodown
/Users/hongli/Projects/passenger/octodown-1.0.4-osx/lib/app/vendor/ruby/2.1.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `require': dlopen(/Users/hongli/Projects/passenger/octodown-1.0.4-osx/lib/app/vendor/ruby/2.1.0/gems/posix-spawn-0.3.9/lib/posix_spawn_ext.bundle, 9): Library not loaded: /usr/local/lib/libgmp.10.dylib (LoadError)
  Referenced from: /Users/hongli/Projects/passenger/octodown-1.0.4-osx/lib/app/vendor/ruby/2.1.0/gems/posix-spawn-0.3.9/lib/posix_spawn_ext.bundle
  Reason: Incompatible library version: posix_spawn_ext.bundle requires version 13.0.0 or later, but libgmp.10.dylib provides version 12.0.0 - /Users/hongli/Projects/passenger/octodown-1.0.4-osx/lib/app/vendor/ruby/2.1.0/gems/posix-spawn-0.3.9/lib/posix_spawn_ext.bundle
```

I've added support for posix-spawn, nokogumbo, github-markdown and escape_utils to Traveling Ruby. But rugged and charlock_holmes need custom work to make them portable.

**Comment by ianks** [comment]
Yeah I was curious about that. Would having Homebrew build bottles for each version of OSX help? Thanks for adding support for those libs. Are you just statically compiling all of the libraries necessary for posix-spawn, etc? That's probably safest, but I wonder what we can get away with as far a dynamic linking goes is OSX.

**Comment by FooBarWidget** [comment]
> Yeah I was curious about that. Would having Homebrew build bottles for each version of OSX help? 

I think so, but even then you've only addressed OS X, not Linux.

> Are you just statically compiling all of the libraries necessary for posix-spawn, etc?

Yes, but the static libraries must also be compiled with specific flags to make them portable, and sometimes I need to patch the build system to make static linking work properly. This is why it involves a lot of custom work. Dynamic linking also works, but it makes distribution trickier.

**Comment by FooBarWidget** [comment]
All native extensions have been packaged. They will be available in the next Traveling Ruby version.

**Comment by ianks** [comment]
Awesome work @FooBarWidget. Thank you for that. Do you mind PRing the Travelling Ruby version when it is released?

**Comment by FooBarWidget** [comment]
I would prefer if you do it, since you are much more familiar with the octodown codebase than I am. :) I only occasionally work on Traveling Ruby during the weekends.

**Comment by ianks** [comment]
Ok, awesome. I just wanted to make sure I didn't miss the update :)

**Comment by FooBarWidget** [comment]
Traveling Ruby 20150130 has been released.

**Comment by FooBarWidget** [comment]
Are you downloading and extracting our native extensions properly? I cannot find any code in your Rake tasks that do that. The native extensions are external tarballs, and each one is explicitly opt-in. They're not included in the default Traveling Ruby tarball.

**Comment by ianks** [comment]
Yeah that's still on the to-do list. Need to make sure to do that before releasing Homebrew formula.
