### ISSUE TITLE
Traveling Ruby package contains redundant files

### ISSUE THREAD

**Issue by FooBarWidget** [ianks/octodown#47]
The files in the directory lib/app/vendor/ruby/2.1.0/cache are redundant. If you remove them you will save 19 MB in your package.

You can probably also remove the directories lib/app/vendor/ruby/2.1.0/gems/*/{test,spec}. This will shave off 9.5 MB of uncompressed files.

You have native extension files inside lib/app/vendor/ruby/2.1.0/gems. Some of these native extensions are duplicates of the ones in lib/app/vendor/ruby/2.1.0/extensions, and can be removed (e.g. nokogiri.bundle). Others are not supplied by Traveling Ruby, and thus are problematic (see #46).

**Comment by FooBarWidget** [comment]
See also the guide: [Reducing the size of your Traveling Ruby packages](https://github.com/phusion/traveling-ruby/blob/master/REDUCING_PACKAGE_SIZE.md)

**Comment by ianks** [comment]
Much if this was dealt with in https://github.com/ianks/octodown/pull/55. There may be a few more files to remove, but the bulk of them are gone.
