### ISSUE TITLE
Update packages for travelling-ruby

### ISSUE THREAD

**Issue by ianks** [ianks/octodown#85]
To release a new build with travelling Ruby, I need a few new gems in the Travelling Ruby repo.

Namely,

```
    'rugged-0.24.0b0',
    'nokogumbo-1.4.1',
    'github-markdown-0.6.9',
    'escape_utils-1.1.0',
    'charlock_holmes-0.7.3',
    'thin-1.6.4',
    'eventmachine-1.0.8',
    'ffi-1.9.10'
```

@FooBarWidget When you get some time, can you look into this?

**Comment by FooBarWidget** [comment]
Traveling Ruby already provides all those gems, just not the same version number. Can't you lock against the version numbers already provided by Traveling Ruby?
