### ISSUE TITLE
Live reload doesn't work when Vim does a rename-and-write

### ISSUE THREAD

**Issue by ches** [ianks/octodown#90]
Hi,

I'd love this to work, but it just isn't for me.

If I run `octodown --live-reload README.md` the rendered preview is launched in my browser successfully, and log output shows `Recompiling markdown…` when I make changes and save, but the preview content never updates. Even if I manually run another separate `octodown README.md` process _while the file watch/server is still running_, the temp file that's opened reflects no changes to the rendered output. Only when I `Ctrl-C` the server and start up a new process are updates reflected. Seems like a caching or locking issue?

In Chrome Dev Tools I see no errors, and inspecting WebSocket frames shows that updates are being received with each file event, but their data is the same in every frame, never reflecting content changes.

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

$ gem list octodown

*** LOCAL GEMS ***

octodown (1.4.2)
```

Let me know if there's any further info that would help.

**Comment by ianks** [comment]
Strange, I have not experienced this. Which version of Ruby are you using?

**Comment by ches** [comment]
Ruby version is above 😉

**Comment by ches** [comment]
Also, I'm on OS X Yosemite. Nothing unusual about the filesystem in question.

**Comment by ianks** [comment]
This smells like a file synchronization situation. 

## Possible cause

fsevent indicates that the file has been modified, yet the data has not synchronized to disk; thus when reading the file, the changes are not seen. This could be tested by doing something like running the `sync` command before reading the file.

Unfortunately, I do not have OSX (or I guess its macOS now, eh :trollface:). I cannot test this out ATM. HOWEVER, if you (or someone else) are feeling gracious, [here is where we could ensure the file system is synced before rendering](https://github.com/ianks/octodown/blob/master/lib/octodown/renderer/server.rb#L123).

Sorry I cannot be of more help right now, but I will try to get on a Mac to try this out ASAP. Thanks for the report @ches

**Comment by ches** [comment]
Thanks @ianks, I'll try to do some deeper debugging when time permits.

**Comment by ches** [comment]
Okay, some more info:

I realized that the problem only manifests when I'm editing with Vim, with some other editors it works fine.  So it's like [this problem][1]. If I set the following in my `vimrc` all is well:

```vim
set nobackup
set noswapfile
set nowritebackup
```

However, I've used Guard with Vim for years without this problem, so there must be some workaround or perhaps an approach to telling Listen how to handle this without having to ask Vim users to make these changes (possibly against their wishes). I'd like to leave this open to dig into that possibility. I'll re-title.

Anyone else interested in looking into it, see [here][2] for some details on how Vim writes files under various config conditions.

[1]: https://github.com/gorakhargosh/watchdog#about-using-watchdog-with-editors-like-vim
[2]: http://vimhelp.appspot.com/editing.txt.html#writing

**Comment by ches** [comment]
In particular, it's notable that I observed that file events *are* triggered, just the content changes aren't reflected. I need to more closely follow how Octodown is working, but this makes me suspect that a specific file handle is always held onto, instead of freshly looking at whatever contents are in the file at the observed *path* after an event occurs, if that makes sense (the link you provided seems to confirm this, where the class instance holds a `file` attribute and `rewind` gets called on it).

There are a bunch of Vim settings involved so it gets a bit confusing, but I *think* Vim's defaults basically work like this:

1. Writing a file creates a backup temporarily, deleting it after write is successful.
2. The backup is done *by renaming the original file and writing the buffer to a new file with the original name*.

(Note: even more confusingly, on some *nixes specifically—but not OS X by my observation—the default behavior of `2.` is instead to *copy* the original file to a backup and overwrite the original, meaning my problem probably won't manifest at all. See [the 'backupcopy' option][1] and set it to "no" or "auto" to get my OS X behavior).

So if a file handle is being retained, it's just pointing to the original file which has been renamed without any changes written to it.

Would it be possible for Octodown to re-read the file at the observed path upon each event, instead of re-using a handle? Any negative effects to that, other than slight overhead?

[1]: http://vimhelp.appspot.com/options.txt.html#%27backupcopy%27

**Comment by ianks** [comment]
I think it would be possible to do something like this (untested) code:

 ```ruby
     def render_md(f)
        file_to_render = File.new(f.path, 'r')
        f.close
        Renderer::GithubMarkdown.render file_to_render, options
      end
```

Can you try this out to see if this fixes your issue?

**Comment by kahnjw** [comment]
I'm experiencing this as well. Adding those configurations to my vimrc didn't help. I don't have time now, but will dig in deeper later. @ianks, if you want to pair up and fix this, let me know. I really dislike my current markdown editor and would prefer to use something like this.

**Comment by kahnjw** [comment]
I take it back, those configuration options did work out for me, for some reason had to stop and restart the server. Still, if octodown were compatible with vim on osx out of the box, would be nice :)

**Comment by ches** [comment]
I didn't get a chance to try the suggested patch yet, but it looks pretty promising given what I'd analyzed about the situation before. I'll try to give it a shot soon and report back.

**Comment by ianks** [comment]
@kahnjw yes I want this to work out of the box as well. I don't have an Mac OS box to test this on right now so any input is hugely appreciated on that front. Thanks for the help @ches and @kahnjw!

**Comment by rafasc** [comment]
KDE text editor kate also suffers from the same issue. Was trying to debug vim using kate as an alternative

**Comment by rafasc** [comment]
@ianks's snippet fixes the issue. Tested with vim and kate. Both editors were experiencing the issue. and properly now.
