### ISSUE TITLE
puma dependency needs old openssl version

### ISSUE THREAD

**Issue by rafasc** [ianks/octodown#92]
Tried to install with `gem install octodown` but the version of `puma` this uses needs another version of openssl. This particular issue is fixed if `puma >= 3.7.0.`

So I cloned the repo and tried with `puma 3.7.0` and the current `3.10.0`. It works properly but 

`bundle exec rake` returns the following: (only copied the failures)
```
Failures:

  1) Integration actually runs...
     Failure/Error: req = Net::HTTP::Get.new('/')
     NameError:
       uninitialized constant Net
     # ./spec/integration_spec.rb:9:in `block (2 levels) in <top (required)>'

  2) Integration fires up a websocket
     Failure/Error: req = Net::HTTP::Get.new('/')
     NameError:
       uninitialized constant Net
     # ./spec/integration_spec.rb:33:in `block (2 levels) in <top (required)>'

Finished in 0.293 seconds (files took 0.58069 seconds to load)
23 examples, 2 failures

Failed examples:

rspec ./spec/integration_spec.rb:2 # Integration actually runs...
rspec ./spec/integration_spec.rb:26 # Integration fires up a websocket

Randomized with seed 33493
```
Not sure if those are real failures or some missed `require` / hardcoded ports that didn't match.

**Comment by ianks** [comment]
Thanks for the report! What happens when you `require 'net/http'`?

**Comment by rafasc** [comment]
adding `require 'net/http'` to `integration_spec.rb`
results in
```
Failures:

  1) Integration fires up a websocket
     Failure/Error: http.request(req)
     Net::HTTPBadResponse:
       wrong status line: "\x00<h1>Hello world!</h1>"
     # ./spec/integration_spec.rb:43:in `block (3 levels) in <top (required)>'
     # ./spec/integration_spec.rb:42:in `block (2 levels) in <top (required)>'
```
Tried to investigate a little further with little success. Ruby is not my forte.

From what I gathered, this sometimes happens when trying to access a ssl enabled page without ssl. But as far as I know the http server is not using ssl. 😕

**Comment by rafasc** [comment]
Not sure if this is an actual bug. It just seems that `net:http` is unable to deal with the websocket connection.
Since the program is working as intended, I rewrote the test using the `faye/websocket` and `eventmachine`.  
It's not ready for a [PR](/rafasc/octodown/tree/websocket-test) because I am new to Ruby but I'll accept suggestions 😃.

**Comment by ianks** [comment]
Don't worry too much about not knowing ruby well. Any contribution would be greatly appreciated and merged once review passes!
