### ISSUE TITLE
Update unsupported dependencies.

### ISSUE THREAD

**Issue by rafasc** [ianks/octodown#96]
Some of the dependencies we use are no longer supported.

For example: the [pipeline filter needed](https://github.com/github-archive/task_list) to fix issue #78 is no longer supported or updated by GitHub. Fortunately, there's an active [fork.](https://github.com/deckar01/task_list)

github-markdown is also unsupported.  [html-pipeline](https://github.com/jch/html-pipeline) >=2.6.0 replaced it with  [commonmarker](https://github.com/gjtorikian/commonmarker)

From my quick investigation, so far, the only one that seems to be problematic is [listen](https://github.com/guard/listen/) because they only support ruby >= 2.2.~~4~~5

I updated these, and it passed tests (ruby 2.4.2p198)
```
'github-markup',              '~> 1.6.1'
'github-linguist',            '~> 5.2.0'
'html-pipeline',              '~> 2.7.0'
'commonmarker',               '~> 0.17.2'
'gemoji',                     '~> 3.0.0'
'html-pipeline-rouge_filter', '~> 1.0.4'
'deckar01-task_list',         '~> 2.0.0' # <- this provides the checkbox support
'launchy',                    '~> 2.4.3'
'rack',                       '~> 2.0.3'
'listen',                     '~> 3.0.3' # investigate (3.1.5 is the current version)
'faye-websocket',             '~> 0.10.7'
'puma',                       '~> 3.10.0'
```
Should we update these (listen included) and drop support of outdated ruby versions?

**Comment by ianks** [comment]
> Should we update these (listen included)

Absolutely. I think we should keep these up to date as long as it does not break functionality.

>  drop support of outdated ruby versions?

My main requirement is that octodown should work with whatever the default ruby is on the majority of developer machines. Maybe something like default version of ruby installed on the 2 most recent mac versions? I'm not a mac user, so I am not sure what that would be. 

As for Linux, Ubuntu 16.04 is now using ruby-2.3 I believe, with Ubuntu 14.04 using ruby-1.9.3. 

Overall >= 2.2.4 seems reasonable, as long as it comes installed by default on recent versions of OSX.

**Comment by rafasc** [comment]
If we're asking mac users to use brew to install dependencies, couldn't we add ruby to that list? That way mac users would use the latest ruby version.

Ruby main page says :
> On OS X El Capitan, Yosemite, Mavericks, and macOS Sierra, Ruby 2.0

But according with https://www.ruby-lang.org/en/downloads/branches/ even 2.1 is already unsupported. And 2.2 will be in unsupported in ~6 months.

Another option that might make more sense is to use less restrictive rules and let bundler figure out which version to use. Something like this:
```
  spec.add_dependency 'github-markup',              '~> 1.4'
  spec.add_dependency 'github-linguist',            '~> 5.0'
  spec.add_dependency 'html-pipeline',              '~> 2.4'
  spec.add_dependency 'commonmarker',               '~> 0.14'
  spec.add_dependency 'gemoji',                     '~> 3.0'
  spec.add_dependency 'html-pipeline-rouge_filter', '~> 1.0', '>= 1.0.2'
  spec.add_dependency 'launchy',                    '~> 2.4', '>= 2.4.3'
  spec.add_dependency 'rack',                       '~> 2.0'
  spec.add_dependency 'listen',                     '~> 3.1'
  spec.add_dependency 'faye-websocket',             '~> 0.10'
  spec.add_dependency 'puma',                       '~> 3.10'

  spec.add_development_dependency 'rspec',     '~> 3.3'
  spec.add_development_dependency 'rubocop',   '~> 0.34'
  spec.add_development_dependency 'bundler',   '~> 1.7'
  spec.add_development_dependency 'rake',      '~> 12.1'
  spec.add_development_dependency 'rack-test', '~> 0.6'

```
We're still bound to >= 2.2.5 because of Listen.

https://github.com/ianks/octodown/compare/ianks:master...rafasc:dev
I'll wait for input before doing a PR

**Comment by ianks** [comment]
> If we're asking mac users to use brew to install dependencies, couldn't we add ruby to that list? That way mac users would use the latest ruby version.

That is very true. Overall, I think supporting Ruby >= 2.2.5 makes a lot of sense. I am on board with it.
